authapp/authapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),

]

authapp/users/urls.py
from . import views as v
from django.urls import path
from django.contrib.auth.urls import views


app_name = 'users'

urlpatterns = [
    path('signup/', v.SignUp.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

]

authapp/users/models.py
from django.db import models

# Create your models here.

authapp/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username',)

authapp/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . forms import CreationForm
from django.shortcuts import render


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('home')
    template_name = 'users/signup.html'


def home(request):
    template = 'home.html'
    key = 'Главная'
    context = {
        'key': key,
    }
    return render(request, template, context)

authapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" href="{% static 'image/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
		{% block title %}
		{% endblock %}
	</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

authapp/templates/home.html
{% extends 'base.html' %}

{% block title %}{{ key }}{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6 p-5">
    <div class="card">
      <div class="card-header">
        <div class="card-body">
          <h1>Вы находитесь на главной</h1>
            <hr>
              {% if user.is_authenticated %}
                <h5>Привет {{ user.username }}</h5>
                <a href="{% url 'users:logout' %}">Выйти</a>
              {% else %}
            <div class="col-md-6 offset-md-4">
                <a href="{% url 'users:login' %}">Войти</a> |
                <a href="{% url 'users:signup' %}">Регистрация</a>
              {% endif %}
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

authapp/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}


  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <div class="alert alert-danger">
          {{ error }}
        </div>
      {% endfor %}
    {% endfor %}
<div class="row justify-content-center">
  <div class="col-md-6 p-5">
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|ljust:"10" }}
            </div>
  </div>
</div>
    {% endfor %}
  {% endif %}


<div class="row justify-content-center">
  <div class="col-md-6 p-5">
    <div class="card">
      <div class="card-header">
        <div class="card-body">
          <form method='post' action="{% url 'users:login' %}">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row my-6 p-3">
            <label for="{{ field.id_for_label }}">
            {{ field.label }}
            </label>
          {{ field }}
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
          <button type="submit" class="btn btn-primary">Принять</button>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
    {% endblock %}

authapp/templates/users/logout.html
{% extends 'base.html' %}

{% block title %}Выход{% endblock %}

{% block content %}

{% endblock %}

authapp/templates/users/signup.html
{% extends 'base.html' %}
{% block title %}Регистрация{% endblock %}
</head>
<body>
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6 p-5">
    <div class="card">
      <div class="card-header">
        <div class="card-body">
          <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-6 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {{ field }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
            {% endfor %}
          <div class="col-md-6 offset-md-4">
          <button type="submit" class="btn btn-primary">
          Зарегистрироваться
          </button>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
</body>
</html>